# Generated by Django 4.2.5 on 2023-09-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_supplier_inventory_amount_inventory_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
